### ISSUE TITLE
[Feature Request] Update Saved Group

### ISSUE THREAD

**Issue by Ineluki** [bit-tinker/Window-Saver#1]
Nice addon so far, could become a replacement for tab groups, but right now there seems to be no way to update a group but delete the old one and save it under the same name again?

It would make a lot of sense for usability of the addon knew which group was opened in which window (if any) and you'd be able to update it with one click (or auto-save it on close)

**Comment by bit-tinker** [comment]
Have you tried the "override saved window" button (arrow down symbol, left of the delete button) and if it does not fulfill your usecase could you elobarate further? 

Do you have so many saved windows that choosing the right one to override in the list becomes tiresome or do you want to edit a saved group within the extension UI, instead of by loading a saved window, changing the open tabs and overriding the saved window?

If "override" does what you want and you didn't find or try it, I suppose the UI could do with some clarification...

**Comment by Ineluki** [comment]
I did not try this yet because it eluded me that the tooltips said something completely different from what the icons seemed to suggest. (I thought the arrows were just for sorting, because, y'know, arrows)

Yep, that works nicely. This can be closed but I'd recommend some more intuitive icons ;)
